// src/solid/client/components/forms/ResetPassword.tsx
// packages/convex-better-auth/src/solid/client/components/forms/ResetPassword.tsx

/**
 * Reset Password Page Component for Solid
 * Handles layout and design for the password reset page
 * Form logic is delegated to ResetPasswordForm
 */

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@tanstack-app/ui/solid'
import { useSearch } from '@tanstack/solid-router'
import { Show, type Component } from 'solid-js'
import ResetPasswordForm from './ResetPasswordForm'

/**
 * Reset Password page component with layout
 * Use this in your TanStack Router routes
 *
 * @example
 * ```tsx
 * // In your route file:
 * import { ResetPassword } from '@convex-better-auth/solid/client/forms'
 *
 * export const Route = createFileRoute('/reset-password')({
 *   component: ResetPassword,
 * })
 * // URL: /reset-password?token=abc123
 * ```
 */
export const ResetPassword: Component = () => {
  const searchParams = useSearch({ strict: false })
  const token = () => (searchParams as any).token

  return (
    <div class="min-h-screen w-full flex items-center justify-center p-4">
      <div class="w-full max-w-md">
        <Show
          when={token()}
          fallback={
            <Card>
              <CardHeader>
                <CardTitle class="text-lg md:text-xl">Invalid Link</CardTitle>
                <CardDescription class="text-xs md:text-sm">
                  This password reset link is invalid or has expired. Please
                  request a new one.
                </CardDescription>
              </CardHeader>

              <CardFooter>
                <div class="flex justify-center w-full border-t py-4">
                  <p class="text-center text-xs text-neutral-500">
                    Powered by{' '}
                    <a
                      href="https://better-auth.com"
                      class="underline"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <span class="dark:text-orange-200/90">better-auth.</span>
                    </a>
                  </p>
                </div>
              </CardFooter>
            </Card>
          }
        >
          <Card>
            <CardHeader>
              <CardTitle class="text-lg md:text-xl">Reset Password</CardTitle>
              <CardDescription class="text-xs md:text-sm">
                Enter your new password below
              </CardDescription>
            </CardHeader>

            <CardContent>
              <ResetPasswordForm token={token()!} />
            </CardContent>

            <CardFooter>
              <div class="flex justify-center w-full border-t py-4">
                <p class="text-center text-xs text-neutral-500">
                  Powered by{' '}
                  <a
                    href="https://better-auth.com"
                    class="underline"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <span class="dark:text-orange-200/90">better-auth.</span>
                  </a>
                </p>
              </div>
            </CardFooter>
          </Card>
        </Show>
      </div>
    </div>
  )
}

export default ResetPassword

// src/client/components/ResetPassword.tsx
// src/client/components/ResetPassword.tsx

import { Button } from '@tanstack-app/ui'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from '@tanstack-app/ui'
import { Input } from '@tanstack-app/ui'
import { Label } from '@tanstack-app/ui'
import { useState } from 'react'
import { Loader2 } from 'lucide-react'
import { authClient } from '../auth-client'
import { useSearch } from '@tanstack/react-router'
import { useNavigate } from '@tanstack/react-router'

export default function ResetPassword() {
  const navigate = useNavigate()
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const searchParams = useSearch({ strict: false })
  const token: string | undefined = (searchParams as any).token

  const handleResetPassword = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!token) return

    if (password !== confirmPassword) {
      alert('Passwords do not match')
      return
    }

    await authClient.resetPassword(
      {
        token,
        newPassword: password,
      },
      {
        onRequest: () => {
          setLoading(true)
        },
        onSuccess: () => {
          setLoading(false)
          void navigate({ to: '/' })
        },
        onError: (ctx) => {
          setLoading(false)
          alert(ctx.error.message)
        },
      },
    )
  }

  if (!token) {
    return (
      <div className="min-h-screen w-full flex items-center justify-center p-4">
        <Card className="max-w-md w-full">
          <CardHeader className="space-y-2">
            <CardTitle className="text-lg md:text-xl">Invalid Link</CardTitle>
            <CardDescription className="text-xs md:text-sm">
              This password reset link is invalid or has expired. Please request
              a new one.
            </CardDescription>
          </CardHeader>
          <CardFooter>
            <div className="flex justify-center w-full border-t py-4">
              <p className="text-center text-xs text-neutral-500">
                Powered by{' '}
                <a
                  href="https://better-auth.com"
                  className="underline"
                  target="_blank"
                >
                  <span className="dark:text-orange-200/90">better-auth.</span>
                </a>
              </p>
            </div>
          </CardFooter>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen w-full flex items-center justify-center p-4">
      <Card className="max-w-md w-full">
        <CardHeader>
          <CardTitle className="text-lg md:text-xl">Reset Password</CardTitle>
          <CardDescription className="text-xs md:text-sm">
            Enter your new password below
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleResetPassword} className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="password">New Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="Enter your new password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            <div className="grid gap-2">
              <Label htmlFor="confirmPassword">Confirm Password</Label>
              <Input
                id="confirmPassword"
                type="password"
                placeholder="Confirm your new password"
                required
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
              />
            </div>

            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? (
                <Loader2 size={16} className="animate-spin" />
              ) : (
                'Reset Password'
              )}
            </Button>
          </form>
        </CardContent>
        <CardFooter>
          <div className="flex justify-center w-full border-t py-4">
            <p className="text-center text-xs text-neutral-500">
              Powered by{' '}
              <a
                href="https://better-auth.com"
                className="underline"
                target="_blank"
              >
                <span className="dark:text-orange-200/90">better-auth.</span>
              </a>
            </p>
          </div>
        </CardFooter>
      </Card>
    </div>
  )
}
