// src/react/client/components/base/OTPInput.tsx
// src/client/components/base/OTPInput.tsx

import { Input } from '@tanstack-app/ui'
import { Label } from '@tanstack-app/ui'

export interface OTPInputProps {
  id: string
  label?: string
  value: string
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  placeholder?: string
  required?: boolean
  disabled?: boolean
  maxLength?: number
  className?: string
}

export function OTPInput({
  id,
  label,
  value,
  onChange,
  placeholder = 'Enter verification code',
  required,
  disabled,
  maxLength = 6,
  className,
}: OTPInputProps) {
  return (
    <div className="space-y-2">
      {label && <Label htmlFor={id}>{label}</Label>}
      <Input
        id={id}
        type="text"
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        required={required}
        disabled={disabled}
        pattern="[0-9]*"
        inputMode="numeric"
        maxLength={maxLength}
        className={className}
      />
    </div>
  )
}

// src/solid/client/components/base/OTPInput.tsx
// src/solid/client/components/base/OTPInput.tsx

import type { Component, JSX } from 'solid-js'
import { Show } from 'solid-js'
import { Input } from '@tanstack-app/ui/solid'
import { Label } from '@tanstack-app/ui/solid'

export interface OTPInputProps {
  id: string
  label?: string
  value: string
  onChange: JSX.EventHandler<HTMLInputElement, InputEvent>
  placeholder?: string
  required?: boolean
  disabled?: boolean
  maxLength?: number
  class?: string
}

export const OTPInput: Component<OTPInputProps> = (props) => {
  return (
    <div class="space-y-2">
      <Show when={props.label}>
        <Label for={props.id}>{props.label}</Label>
      </Show>
      <Input
        id={props.id}
        type="text"
        value={props.value}
        oninput={props.onChange}
        placeholder={props.placeholder ?? 'Enter verification code'}
        required={props.required}
        disabled={props.disabled}
        pattern="[0-9]*"
        inputmode="numeric"
        maxlength={props.maxLength ?? 6}
        class={props.class}
      />
    </div>
  )
}
