// src/solid/client/components/base/PasswordInput.tsx
// src/solid/client/components/base/PasswordInput.tsx

import type { Component, JSX } from 'solid-js'
import { createSignal } from 'solid-js'
import { Input } from '@tanstack-app/ui/solid'
import { Label } from '@tanstack-app/ui/solid'
import Eye from 'lucide-solid/icons/eye'
import EyeOff from 'lucide-solid/icons/eye-off'

export interface PasswordInputProps {
  id: string
  label?: string
  value?: string
  onInput?: JSX.EventHandler<HTMLInputElement, InputEvent>
  onBlur?: JSX.EventHandler<HTMLInputElement, FocusEvent>
  placeholder?: string
  required?: boolean
  disabled?: boolean
  autoComplete?: string
  class?: string
  name?: string
}

export const PasswordInput: Component<PasswordInputProps> = (props) => {
  const [showPassword, setShowPassword] = createSignal(false)

  return (
    <div class="space-y-2">
      {props.label && <Label for={props.id}>{props.label}</Label>}
      <div class="relative">
        <Input
          id={props.id}
          name={props.name}
          type={showPassword() ? 'text' : 'password'}
          value={props.value}
          oninput={props.onInput}
          onblur={props.onBlur}
          placeholder={props.placeholder}
          required={props.required}
          disabled={props.disabled}
          autocomplete={props.autoComplete}
          class={props.class}
        />
        <button
          type="button"
          onclick={() => setShowPassword(prev => !prev)}
          class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
          tabindex="-1"
        >
          {showPassword() ? <EyeOff size={16} /> : <Eye size={16} />}
        </button>
      </div>
    </div>
  )
}

// src/client/components/base/PasswordInput.tsx
// src/client/components/base/PasswordInput.tsx

import { Input } from '@tanstack-app/ui'
import { Label } from '@tanstack-app/ui'
import { Eye, EyeOff } from 'lucide-react'
import { useState } from 'react'

export interface PasswordInputProps {
  id: string
  label?: string
  value?: string
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void
  placeholder?: string
  required?: boolean
  disabled?: boolean
  autoComplete?: string
  className?: string
  name?: string
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void
}

export function PasswordInput({
  id,
  label,
  value,
  onChange,
  placeholder,
  required,
  disabled,
  autoComplete,
  className,
  name,
  onBlur,
}: PasswordInputProps) {
  const [showPassword, setShowPassword] = useState(false)

  return (
    <div className="space-y-2">
      {label && <Label htmlFor={id}>{label}</Label>}
      <div className="relative">
        <Input
          id={id}
          name={name}
          type={showPassword ? 'text' : 'password'}
          value={value}
          onChange={onChange}
          onBlur={onBlur}
          placeholder={placeholder}
          required={required}
          disabled={disabled}
          autoComplete={autoComplete}
          className={className}
        />
        <button
          type="button"
          onClick={() => setShowPassword(!showPassword)}
          className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
          tabIndex={-1}
        >
          {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
        </button>
      </div>
    </div>
  )
}
